project_id = "iuxacgyocpwblpmmbwwc"

[functions]

[functions.get-public-config]
verify_jwt = false

[functions.send-approval-email]
verify_jwt = true

[functions.send-auth-email]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false

[functions.test-google-api]
verify_jwt = false

[functions.fetch-google-place-details]
verify_jwt = false

[functions.backfill-google-ratings]
verify_jwt = false

[functions.send-invite-success-email]
verify_jwt = false

[functions.send-invite-success-email-listener]
verify_jwt = false

[functions.send-community-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.populate-preview-data]
verify_jwt = false
