import { 
  Waves, 
  Thermometer, 
  Zap, 
  Droplets, 
  Trees, 
  Bug, 
  ShowerHead, 
  Hammer, 
  Heart, 
  Sparkles, 
  Car, 
  Settings,
  Filter,
  PaintBucket,
  Palette,
  Truck,
  Shield,
  Building2,
  Flame,
  Lightbulb,
  Sofa,
  Grid3x3,
  Star,
  Layers,
  Wine,
  Scroll,
  Sprout,
  LucideIcon 
} from "lucide-react";
import { Category } from "@/data/categories";

export const categoryIconMap: Record<Category, LucideIcon> = {
  "Pool": Waves,
  "HVAC": Thermometer,
  "Electrician": Zap,
  "Grill Cleaning": Flame,
  "Plumbing": Droplets,
  "Painters": PaintBucket,
  "Landscaping": Trees,
  "Landscape Lighting": Lightbulb,
  "Generator": Zap,
  "Pest Control": Bug,
  "Power Washing": ShowerHead,
  "Car Wash & Detail": Car,
  "Handyman": Hammer,
  "Pet Grooming": Heart,
  "House Cleaning": Sparkles,
  "House Manager": Building2,
  "Mobile Tire Repair": Car,
  "Appliance Repair": Settings,
  "Auto Transport": Truck,
  "Bartenders": Wine,
  "Water Filtration": Filter,
  "Interior Design": Palette,
  "Moving Company": Truck,
  "Damage Assessment/Restoration": Shield,
  "Carpet/Upholstery Cleaning": Sofa,
  "Patio Screening": Grid3x3,
  "Holiday Lighting": Star,
  "Tile Installation": Layers,
  "Turf Installation": Sprout,
  "Wallpaper Installation": Scroll,
};

export function getCategoryIcon(category: Category): LucideIcon {
  return categoryIconMap[category] || Settings;
}